swagger: "2.0"
info:
  version: "1.0.0"
  title: "Data Collection API"
  description: >
    Microservice for collecting and managing event data from external sources for
    the SENG3011 Team Tango project.

host: "127.0.0.1"
schemes:
  - "https"
basePath: "/"

consumes:
  - "application/json"
produces:
  - "application/json"

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: >
      Provide JWT token as: "Bearer <token>"

tags:
  - name: "General"
    description: "Endpoints for docs and health checks."

  - name: "Data Collection"
    description: "Create/manage datasets and fetch/manage events for a user."

definitions:
  ErrorResponseDataset:
    type: object
    required: [error, message]
    properties:
      error:
        type: string
        example: "INVALID_PARAMETERS"
      message:
        type: string
        example: "Invalid request parameter: name."

  ErrorResponseDatasetNotFound:
    type: object
    required: [error, message]
    properties:
      error:
        type: string
        example: "DATASET_NOT_FOUND"
      message:
        type: string
        example: "Invalid dataset id."

  StatusResponse:
    type: object
    properties:
      status:
        type: string
        example: "ok"
      timestamp:
        type: string
        format: date-time
        example: "2026-03-11T12:00:00.000Z"

  TimeObject:
    type: object
    required: [timestamp, timezone]
    properties:
      timestamp:
        type: string
        example: "2026-03-01 00:00:00"
      duration:
        type: integer
        example: 1
      duration_unit:
        type: string
        example: "day"
      timezone:
        type: string
        example: "UTC"

  AdageEvent:
    type: object
    required: [time_object, event_type, attribute]
    example:
      time_object:
        timestamp: "2026-03-01 00:00:00"
        timezone: "UTC"
        duration: 1
        duration_unit: "day"
      event_type: "stock_ohlc"
      attribute:
        symbol: "AAPL.XNAS"
        name: "Apple Inc"
        exchange: "NASDAQ"
        exchange_code: "XNAS"
        open: 184.2
        high: 187.9
        low: 183.5
        close: 186.7
        volume: 58230000
        adj_open: 184.2
        adj_high: 187.9
        adj_low: 183.5
        adj_close: 186.7
        adj_volume: 58230000
        split_factor: 1.0
        dividend: 0.0
        currency: "USD"
    properties:
      time_object:
        $ref: "#/definitions/TimeObject"
      event_type:
        type: string
        example: "stock_ohlc"
      attribute:
        type: object
        additionalProperties: true

  AdageData:
    type: object
    required: [dataset_id, data_source, dataset_type, time_object, events]
    example:
      dataset_id: "dataset_1741651200000_1"
      data_source: "MarketStack"
      dataset_type: "daily_stock_data"
      time_object:
        timestamp: "2026-03-11T12:00:00.000Z"
        timezone: "UTC"
      events:
        - time_object:
            timestamp: "2026-03-01 00:00:00"
            timezone: "UTC"
            duration: 1
            duration_unit: "day"
          event_type: "stock_ohlc"
          attribute:
            symbol: "AAPL.XNAS"
            name: "Apple Inc"
            exchange: "NASDAQ"
            exchange_code: "XNAS"
            open: 184.2
            high: 187.9
            low: 183.5
            close: 186.7
            volume: 58230000
            adj_open: 184.2
            adj_high: 187.9
            adj_low: 183.5
            adj_close: 186.7
            adj_volume: 58230000
            split_factor: 1.0
            dividend: 0.0
            currency: "USD"
    properties:
      dataset_id:
        type: string
        example: "dataset_1741651200000_1"
      data_source:
        type: string
        example: "MarketStack"
      dataset_type:
        type: string
        example: "daily_stock_data"
      time_object:
        $ref: "#/definitions/TimeObject"
      events:
        type: array
        items:
          $ref: "#/definitions/AdageEvent"

  EventsRequest:
    type: object
    properties:
      symbols:
        type: array
        items:
          type: string
        example: ["AAPL.XNAS", "MSFT.XNAS"]
      exchange:
        type: string
        example: "XNAS"
      date_from:
        type: string
        format: date
        example: "2026-02-01"
      date_to:
        type: string
        format: date
        example: "2026-03-01"
      sort:
        type: string
        enum: ["ASC", "DESC"]
        example: "DESC"
      limit:
        type: integer
        example: 100
      offset:
        type: integer
        example: 0

  RemoveEventsRequest:
    type: object
    properties:
      symbols:
        type: array
        items:
          type: string
        example: ["AAPL.XNAS", "MSFT.XNAS"]
      exchange:
        type: string
        example: "XNAS"
      date_from:
        type: string
        format: date
        example: "2026-02-01"
      date_to:
        type: string
        format: date
        example: "2026-03-01"

  FetchEventsResponse:
    type: object
    required: [count, dataset]
    properties:
      count:
        type: integer
        example: 124
      dataset:
        $ref: "#/definitions/AdageData"

  RemoveEventsResponse:
    type: object
    required: [count]
    properties:
      count:
        type: integer
        example: 124

  DatasetCreateRequest:
    type: object
    required: [name]
    properties:
      name:
        type: string
        example: "Some Tech Stocks Q1 2026"
      description:
        type: string
        example: "Data for listed tech companies"
      symbols:
        type: array
        items:
          type: string
        example: ["AAPL.XNAS", "MSFT.XNAS"]
      exchange:
        type: string
        example: "XNAS"

  DatasetUpdateRequest:
    type: object
    properties:
      name:
        type: string
        example: "Other name"
      description:
        type: string
        example: "Other description"
      symbols:
        type: array
        items:
          type: string
        example: ["AAPL.XNAS", "MSFT.XNAS"]
      exchange:
        type: string
        example: "XNAS"

  DatasetRemoveResponse:
    type: object
    required: [count]
    properties:
      count:
        type: integer
        example: 1

  DatasetListResponse:
    type: array
    items:
      $ref: "#/definitions/AdageData"

paths:
  /v0/docs:
    get:
      tags: ["General"]
      summary: "Retrieve Swagger documentation"
      produces: ["text/html"]
      responses:
        200:
          description: "Swagger documentation (rendered)"
          schema:
            type: string
            example: "<!DOCTYPE html><html>...</html>"

  /v0/status:
    get:
      tags: ["General"]
      summary: "Check API health"
      responses:
        200:
          description: "API status"
          schema:
            $ref: "#/definitions/StatusResponse"

  /v1/datasets:
    post:
      tags: ["Data Collection"]
      summary: "Create a new dataset"
      security:
        - BearerAuth: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/DatasetCreateRequest"
      responses:
        201:
          description: "Dataset created"
          schema:
            $ref: "#/definitions/AdageData"
        400:
          description: "Invalid dataset parameters"
          schema:
            $ref: "#/definitions/ErrorResponseDataset"

    get:
      tags: ["Data Collection"]
      summary: "List all datasets"
      security:
        - BearerAuth: []
      responses:
        200:
          description: "List of datasets"
          schema:
            $ref: "#/definitions/DatasetListResponse"

  /v1/datasets/{dataset_id}:
    get:
      tags: ["Data Collection"]
      summary: "Retrieve a dataset (with events)"
      security:
        - BearerAuth: []
      parameters:
        - name: dataset_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Dataset"
          schema:
            $ref: "#/definitions/AdageData"
        404:
          description: "Dataset not found"
          schema:
            $ref: "#/definitions/ErrorResponseDatasetNotFound"

    put:
      tags: ["Data Collection"]
      summary: "Modify a dataset"
      security:
        - BearerAuth: []
      parameters:
        - name: dataset_id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/DatasetUpdateRequest"
      responses:
        200:
          description: "Dataset updated"
          schema:
            $ref: "#/definitions/AdageData"
        404:
          description: "Dataset not found"
          schema:
            $ref: "#/definitions/ErrorResponseDatasetNotFound"

    delete:
      tags: ["Data Collection"]
      summary: "Remove a dataset"
      security:
        - BearerAuth: []
      parameters:
        - name: dataset_id
          in: path
          required: true
          type: string
      responses:
        200:
          description: "Dataset removed"
          schema:
            $ref: "#/definitions/DatasetRemoveResponse"
        404:
          description: "Dataset not found"
          schema:
            $ref: "#/definitions/ErrorResponseDatasetNotFound"

  /v1/datasets/{dataset_id}/events/fetch:
    post:
      tags: ["Data Collection"]
      summary: "Fetch new events from external APIs into an existing dataset (as ADAGE dataset)"
      security:
        - BearerAuth: []
      parameters:
        - name: dataset_id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/EventsRequest"
      responses:
        200:
          description: "Events fetched successfully"
          schema:
            $ref: "#/definitions/FetchEventsResponse"
        404:
          description: "Dataset not found"
          schema:
            $ref: "#/definitions/ErrorResponseDatasetNotFound"

  /v1/datasets/{dataset_id}/events/remove:
    delete:
      tags: ["Data Collection"]
      summary: "Remove events from an existing dataset (by parameters, similar to fetch)"
      security:
        - BearerAuth: []
      parameters:
        - name: dataset_id
          in: path
          required: true
          type: string
        - in: body
          name: body
          required: false
          schema:
            $ref: "#/definitions/RemoveEventsRequest"
      responses:
        200:
          description: "Events removed successfully"
          schema:
            $ref: "#/definitions/RemoveEventsResponse"
        404:
          description: "Dataset not found"
          schema:
            $ref: "#/definitions/ErrorResponseDatasetNotFound"
